### ISSUE TITLE
Error with other plugin - pmizio/typescript-tools.nvim

### ISSUE THREAD

**Issue by lvim-tech** [kosayoda/nvim-lightbulb#52]
Error with other plugin - pmizio/typescript-tools.nvim

`
Error executing lua callback: /mnt/system/app/neovim10/share/nvim/runtime/lua/vim/lsp.lua:1586: id: expected number, got string
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	/mnt/system/app/neovim10/share/nvim/runtime/lua/vim/lsp.lua:1586: in function 'cancel_request'
	/mnt/system/app/neovim10/share/nvim/runtime/lua/vim/lsp.lua:2134: in function 'lightbulb_lsp_cancel'
	...are/nvim/lazy/nvim-lightbulb/lua/nvim-lightbulb/init.lua:241: in function <...are/nvim/lazy/nvim-lightbulb/lua/nvim-lightbulb/init.lua:202>
`

**Comment by kosayoda** [comment]
Hi, can you share a minimal reproducible example? My initial thoughts are that it might be a bug with `typescript-tools`, since [according to the docs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#cancelRequest) request cancellation takes a `integer | string`.

**Comment by lvim-tech** [comment]
Yes, I think this is a typescript-tools.nvim issue
I removed it.
Thanks for your work!
